---
- name: Install software-properties-common
  ansible.builtin.apt:
    name: software-properties-common
    update_cache: true
    state: present

- name: Add i386 architecture
  ansible.builtin.lineinfile:
    path: /var/lib/dpkg/arch
    state: present
    create: true
    insertafter: EOF
    line: i386
    mode: 0644

- name: Accept steam licence
  ansible.builtin.debconf:
    name: steamcmd
    question: steam/question
    value: 'I AGREE'
    vtype: select

- name: Install steamcmd
  ansible.builtin.apt:
    pkg:
      - steamcmd
    update_cache: true
    state: present
